version: "3.9"

services:
  dev-app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
      target: dev
      platforms:
        - linux/amd64
    ports:
      - "4321:1234"
    volumes:
      - ./logs:/srv/app/logs
    container_name: dev-vite-app
    image: dev-vite-app-amd

  prod-app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
      target: prod
    ports:
      - "5432:1234"
    volumes:
      - ./logs:/srv/app/logs
    container_name: prod-vite-app