version: "3.9"

services:
  dev-app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
      target: dev
    ports:
      - "4321:1234"
    volumes:
      - ./logs:/srv/app/logs
    container_name: docker-test-dev

  prod-app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile
      target: prod
    ports:
      - "5432:1234"
    volumes:
      - ./logs:/srv/app/logs
    container_name: docker-test-prod