app:
  env: "dev"
  version: "1.0.0"
  logLevel: "debug"
  sentryDsn: "test.sentry.dsn"
  replicas: 2
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  ports:
    rest: 1234
  nodeSelector:
    role: backend

image:
  repository: "laba21/vite"
  tag: "1.0.0"
