app:
  env: "dev"
  version: "1.0.0"
  logLevel: "debug"
  sentryDsn: "test.sentry.dsn"
  replicas: 2
  resources:
    requests:
      cpu: "200m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  ports:
    rest: 1234
  nodeSelector:
    role: backend

image:
  repository: "laba21/vite"
  tag:
    "1.0.1" # пересобрано Docker-образ із оновленою конфігурацією Vite (vite.config.js),
    # дозволено доступ з доменів у зоні *.dev.acdm.space

ingress:
  enabled: true
  # ВАЖЛИВО: замініть на власний домен, але ОБОВ’ЯЗКОВО в межах *.dev.acdm.space
  # Приклад: vite-anna.dev.acdm.space
  host: vite.dev.acdm.space
