name: Build & Push Docker Image Vite

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag"
        required: true

jobs:
  build:
    name: Build & Push Docker
    runs-on: dev-arc-runner-set

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -f deploy/docker/Dockerfile \
            -t laba21/vite:${{ github.event.inputs.image_tag }} \
            .
        shell: bash

      - name: Push Docker image
        run: docker push laba21/vite:${{ github.event.inputs.image_tag }}
        shell: bash